# AIrTonomy Research Stream Descriptions, Fall 2026

## 1. Reinforcement Learning for Guidance, Navigation, and Control

This subteam explores learning-based policies for path-planning for fixed-wing UAVs using a gymnasium environment. The research focus is Reinforcement Learning for guidance and control (policy learning, reward design, sim-to-real strategies) and how learned policies compare to classical baselines under disturbances and modeling error.

Expected activities include: 1) Literature review 2) Mathematical Problem Formulation 3) Coding a Gymnasium Environment for Dynamic path-planning (no-ROS) that is compatible with the Simulator used for the Fixed-wing drone competition 4) Integration of the RL path-planner with a PID control and State-Simulator 5) Training the RL model for fixed-wing drone in the developed Gymnasium 6) Validating the Path-planner in the Simulator of the Competition, and 7) Deploying it on a real fixed-wing vehicle to be flown in PURT.

## 2. System Identification (SysID) for UAVs

This subteam focuses on System identification (SysID) with a focus on guidance, navigation, and control (GNC). SysID focuses on accurately simulating and predicting the behavior of UAVs, in particular during abnormal flight conditions such as certain maneuvers or external disturbances. SysID also sets the foundation for model-predictive control (MPC), based on accurate state estimation. SysID methods subsume classical and data-driven methods including frequency-based methods, time-domain methods range from output error estimation to neural network-based approaches. The task of SysID is to predict the system's future states but also learning or estimating the parameters of ordinary differential equations (ODE) or even the functional terms of the ODE describing the behavior of the UAV based on input and output data (e.g. velocity, flight path angle, angle of attack, pitch rate). Ongoing research focuses on methods for parameter estimation as well as uncertainty quantification (UQ) and residual approximation in SysID using Bayesian methods. Team members learn about the mathematical foundations of SysID based on readings of foundational literature (e.g. scientific literature), and implement methods based on simulated data of an ordinary differential equation (ODE) of a second-order dynamical system (Mass-Damper) before moving on to 3-DOF aircraft modeling and real-world 6-DOF aircraft data from our industry partner Windracers US LLC and our own collected data using a downscaled version (Sportscub). The final SysID results will be used for the digital twin simulator, used in the fixed-wing drone competition and also for SysID of the industry partner Windracers US LLC. Potential collaboration with other industry partners is also possible (Skydio etc.).

Expected activities include: 1) Literature review 2) Mathematical Formulation of the Method 3) Simulation, Data Collection and Preprocessing 4) Model Implementation for Bayesian SysID 5) Software engineering and vehicle config publishing (e.g. log-to-parameter pipeline), 6) Simulation and sensitivity analysis.

Researchers also have the opportunity to learn how to fly fixed-wing drones, and collect flight data through the collaboration with PURT and SATT.

## 3. Vision-based Navigation and Runway Detection for Safe Landing

This subteam uses computer vision algorithms for runway detection and automated landing. The focus is on creating and improving computer vision and deep learning models towards this end. The process involves data collection, training, evaluation, and testing to achieve realistic automated landing of a fixed-wing on a runway.

Expected activities include: 1) Literature review 2) Data collection and scraping 3) Model Development (building vision models, both classical and deep) 4) Evaluation and testing.

The team member's tasks will be closely defined in collaboration with the industry partner Windracers LLC and other senior researchers within AIDA3.

## 4. Classical Guidance and Control

This subteam develops and characterizes the classical guidance and control stack that every other flight-facing project measures itself against. Work covers lateral guidance for waypoint and loiter tracking, longitudinal energy management for coupled speed and altitude commands, and the inner-loop attitude controllers that sit beneath them, along with the gain tuning and stability margins that make a controller trustworthy on a real airframe rather than only in simulation. Because a learned policy is only interesting if it beats a well-tuned conventional one, a central deliverable is a documented, reproducible baseline: the same mission profiles flown with classical guidance under the same wind, turbulence, and sensor-noise conditions used by the reinforcement learning subteam, with tracking error, control effort, and failure modes reported in a form the two teams can compare directly. The subteam also inherits the trajectory-generation problem of producing flyable paths that respect turn-rate and climb-rate limits, which connects it to the airspace geometry work upstream.

Expected activities include: 1) Literature review on classical fixed-wing guidance laws and autopilot architectures 2) Reconstruction and documentation of the results carried over from spring 3) Implementation of lateral and longitudinal guidance laws in the competition simulator 4) Systematic gain tuning and stability margin analysis against the SysID models 5) Definition of a shared benchmark suite of mission profiles and disturbance conditions 6) Head-to-head evaluation against the learned path-planner 7) Hardware-in-the-loop testing and flight validation at PURT.

Team members will work in Python and the competition simulator alongside the vehicle autopilot configuration. This subteam is a natural entry point for students who want flight dynamics and control fundamentals before moving into the learning-based projects.

## 5. Wind Tunnel Testing and Aerodynamic Characterization

This subteam produces the measured aerodynamic data that the learning and identification projects use as ground truth. A small single-propeller UAV representative of our airframe is mounted in the Boeing Wind Tunnel at Purdue and tested for lift and drag in steady level flight, with the balance calibrated beforehand against known one to ten pound weights so that the recorded forces trace back to a physical standard rather than to a trusted zero. Because the aircraft is powered, the test separates propulsive force from aerodynamic drag by first sweeping the propeller from twenty percent to full throttle in the absence of wind and recording the resulting thrust history, then repeating the sweep with the tunnel running so that the two contributions can be disentangled. Freestream velocity is measured twice over, once from Pitot dynamic pressure and once from a hot film anemometer, and the disagreement between the two is itself a diagnostic. Each test condition is run three times for averaging. The scientific value lies in the comparison downstream: where the tunnel measurements and the parameters fit from flight logs disagree, that disagreement localizes error in the model and tells the SysID team where its assumptions break down.

The existing procedure fixes the aircraft at zero angle of attack, which is sufficient for the steady level flight case but not for populating a coefficient table across the flight envelope. Extending the test to angle of attack and control surface deflection sweeps, and adding pitch and roll moment reduction to the lift and drag already recorded, is open work for this subteam, as is the question of what Reynolds number scaling and tunnel wall corrections do to the numbers before they are handed to the digital twin.

Expected activities include: 1) Literature review on low-speed wind tunnel methods, blockage corrections, and Reynolds number scaling 2) Force balance calibration and verification 3) Model preparation, mounting, and tunnel safety procedures 4) Execution of the powered and unpowered throttle sweeps with repeat trials 5) Reduction of the twelve-channel LabVIEW output into lift and drag coefficients with uncertainty estimates 6) Cross-checking of Pitot and anemometer velocity measurements 7) Extension of the test matrix beyond zero angle of attack 8) Comparison against SysID parameter estimates and publication of the resulting coefficient set for the digital twin.

Team members will work with the Boeing Wind Tunnel, its LabVIEW data acquisition VI and force balance transducers, Pitot and hot film instrumentation, and Python data reduction pipelines. This subteam suits students who want hands-on experimental work and a direct line from measurement to model.

## 6. Bayesian Methods for Modeling and Uncertainty Quantification

This subteam treats uncertainty as a first-class quantity rather than an afterthought. Where a conventional fit returns one set of parameters, a Bayesian treatment returns a distribution over them, and that distribution is what lets a system state how confident it is in a prediction, propagate that confidence forward in time, and decide when it does not know enough to act. The work spans the mathematical foundations, meaning priors, likelihoods, posterior inference, and the practical machinery of Markov chain Monte Carlo and variational approximation, and the application of those foundations to dynamical systems: estimating the parameters and the unmodeled residual terms of the ODEs describing UAV behavior, quantifying how that uncertainty propagates through state estimation, and calibrating the resulting predictive intervals against held-out flight data. The subteam is mathematically demanding and is intended for students with a strong interest in probability, statistics, and differential equations.

Expected activities include: 1) Literature review on Bayesian inference and probabilistic modeling of dynamical systems 2) Working through the tutorial sequence on Bayesian and frequentist foundations 3) Implementation of posterior inference on a second-order dynamical system before moving to aircraft models 4) Development of residual and discrepancy models for unmodeled dynamics 5) Uncertainty propagation through state estimation 6) Calibration and posterior predictive checking against real flight data 7) Documentation of methods as reusable tutorials for the wider team.

Team members will work in Python with probabilistic programming libraries. This subteam collaborates closely with SysID, which supplies the models and data against which the methods are exercised.

## 7. Large Language Models for Safe UAV Operations

This subteam supports research on conversational mission-planning and operations, jointly with PhD students and other researchers. It focuses specifically on the safety of language-based instructions and communications between operators, UAVs, and air-traffic-control. Formal methods such as propositional logic and signal temporal logic play an important role in this. In addition, formal grammars also support methods such as prompt-engineering and fine-tuning of LLMs. This team will focus its efforts on such formal methods and grammars in order to increase the safety of conversational path-planning. The mentors will introduce the team members to ATC communication, STL, and formal grammars. The goal is to evaluate an existing chatbot system through human-subject experiments and to strengthen the safety guarantees on its language-based instructions.

Individual tasks include: 1) Review of existing datasets and of the current system 2) Grammar development and constrained generation for ATC phraseology 3) Testing and evaluation of speech-to-text-to-speech communication 4) User-interface design improvements 5) Recruitment of pilots, ATC experts, and students into chatbot testing, and support of A-B testing and real-world testing 6) Documentation of evaluation protocols and results.

All activities will be performed in alignment with our industry partners, and other stakeholders such as ATC operators, pilots, etc.

## 8. Geospatial Airspace Modeling and Live Operational Awareness

This subteam builds a queryable 3D model of the airspace around an airport by converting published FAA airspace boundaries from 2D polygons into closed solids, then layering live operational data on top. The static layer extrudes each of the 6,054 airspace features between its published floor and ceiling, which requires projection from geographic degrees into a metric frame, terrain-following surface floors, mixed altitude references, the nested shelf structure of Class B airspace, and validation that each solid is watertight rather than merely renderable. Protective geometry including the Part 77 imaginary surfaces and Runway Protection Zones is computed directly from runway survey data. The live layer streams temporary flight restrictions, weather polygons, and ADS-B traffic, with each aircraft represented as a swept capsule sized from its broadcast position quality indicators. The result is a geofence and conflict check for Earhart grounded in real published airspace rather than a hand-drawn boundary, delivered through a browser viewer where every volume is pickable and traceable to its source feed.

The second half of the project turns those solids into specifications. An operator planning a mission today enters airport and constraint information by hand, and the aim here is to replace that with a pipeline in which the operator clicks a region on the map and the system resolves the click against the surrounding airspace solids to produce a formal specification of the constraint, including its spatial extent, its altitude bounds, and its period of validity. The same construction accepts a spoken or written instruction in place of the click, so that a NOTAM or a controller instruction and the geometry it refers to are fused into a single specification. Framed this way the research problem is specification completion from multimodal input, where neither the utterance nor the geometry is sufficient alone, and it gives the formal-methods material taught in the tutorials a concrete target.

Expected activities include: 1) Literature review 2) Mathematical formulation of the extrusion, projection, and capsule intersection problems 3) Implementation of the static extrusion pipeline in Python 4) Computation of Part 77 surfaces and Runway Protection Zones, verified against the published KLAF airport diagram 5) Integration of live NOTAM, weather, and ADS-B feeds 6) Development of the click-based 3D viewer 7) Formulation of the click-plus-geometry to specification pipeline 8) Extension of that pipeline to spoken and written constraint inputs 9) Testing of the conflict predicate against recorded flight tracks 10) Publication of the derived airspace solids as open data.

Team members will work with QGIS, Python geospatial libraries including shapely, pyproj, and trimesh, and either CesiumJS or deck.gl. Researchers have the opportunity to connect this work to flight operations at PURT and to coordinate with the vision-based navigation subteam, which shares the same runway geometry data.

## 9. ATC and ADS-B Data Mining for Open Aviation Datasets

This subteam builds the dataset that the language and airspace projects both need and that does not currently exist in usable form. Controller and pilot radio traffic is publicly streamed from airports including Purdue University Airport and can be captured continuously, but audio alone carries no record of which aircraft was where when a given instruction was issued. The work is to record that audio alongside ADS-B surveillance data from the OpenSky Network, align the two on a common clock so that every utterance sits against the traffic picture it was spoken into, and then label the aligned pairs against a ground-truth grammar of standard phraseology. Labeling is where the research sits rather than where the drudgery sits, because the interesting cases are the ones where real phraseology departs from the standard, and cataloguing those departures is what makes the dataset worth publishing. Students are trained on the phraseology and the grammar before labeling, which makes this an effective entry point for newcomers, and the intended outcome is a public dataset and an accompanying dataset paper.

Expected activities include: 1) Review of existing ATC speech and surveillance datasets 2) Setup and operation of continuous audio capture at selected airports 3) Retrieval and preprocessing of matching ADS-B tracks 4) Timestamp alignment and segmentation of utterances against traffic state 5) Transcription and grammar-based annotation with an agreed ground truth 6) Inter-annotator agreement measurement and quality control 7) Cataloguing of departures from standard phraseology 8) Release of the dataset as open data and preparation of a dataset paper.

Team members will work in Python with speech processing and grammar tooling, and will complete the formal grammars tutorial before annotation begins. This subteam works in close coordination with the large language model subteam, which consumes the resulting dataset.
